name: Docker Build

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]

env:
  UBUNTU_VERSION: 24.04
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  cpu-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - { latest: "false", python: "3.11", venv: "python_311" }
    steps:
      - name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cpu"
          base_tag="${{ matrix.build.python }}-v2-cpu-${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              # GHCR.io Tags
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
              # Docker.io tags
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest"
          else  
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=ghcr.io/starforge-ai/base-image:v2-cpu-${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ matrix.build.python }}
            PYTHON_VENV_NAME=${{ matrix.build.venv }}
          push: true
          # Avoids unknown/unknown architecture and extra metadata
          provenance: false
          tags: ${{ env.TAGS }}

  nvidia-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "13.1.0-base",
           }
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "13.0.2-base",
           }  
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "13.0.2-cudnn-runtime",
           }
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "13.0.2-cudnn-devel",
           } 
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "12.9.1-base",
           }  
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "12.9.1-cudnn-runtime",
           }
         - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              cuda: "12.9.1-cudnn-devel",
           }           
    steps:
      - name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
          base_tag="${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              # GHCR.io Tags
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cuda, ${img_path_ghcr}:latest"
              # Docker.io Tags
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest"
          else  
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=ghcr.io/starforge-ai/base-image:v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ matrix.build.python }}
            PYTHON_VENV_NAME=${{ matrix.build.venv }}
          push: true
          provenance: false
          tags: ${{ env.TAGS }}

  amd-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              rocm: "7.0.3-core",
            }
          - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              rocm: "7.0.3-runtime",
            }
          - {
              latest: "false",
              python: "3.11",
              venv: "python_311",
              rocm: "7.0.3-devel",
            }
    steps:
      - name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
          base_tag="${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              # GHCR.io Tags
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
              # Docker.io Tags
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest"
          else  
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: build
          build-args: |
            IMAGE_BASE=ghcr.io/starforge-ai/base-image:v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
            PYTHON_VERSION=${{ matrix.build.python}}
            PYTHON_VENV_NAME=${{ matrix.build.venv }}
          push: true
          provenance: false
          tags: ${{ env.TAGS }}
